CREATE TABLE IF NOT EXISTS House (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "uuid" UUID NOT NULL,
    area INT NOT NULL,
    country VARCHAR(50) NOT NULL,
    city VARCHAR(50) NOT NULL,
    street VARCHAR(50) NOT NULL,
    number INT NOT NULL,

    create_date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Person(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "uuid" UUID NOT NULL,
    name VARCHAR(30) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    sex CHAR(1) NOT NULL,
    passport_series CHAR(2) NOT NULL,
    passport_number CHAR(13) NOT NULL,

    create_date TIMESTAMP NOT NULL,
    update_date TIMESTAMP NOT NULL,

    house_of_residence_id BIGINT REFERENCES House(id) ON UPDATE CASCADE NOT NULL,

    CONSTRAINT uq_combination_passport_series_and_passport_number
        UNIQUE(passport_series, passport_number)
);

CREATE TABLE IF NOT EXISTS Owner_OwnedHouse(
    person_id BIGINT REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    house_id BIGINT REFERENCES House(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,

    CONSTRAINT pk PRIMARY KEY (person_id, house_id)
);



