spring:
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: size
        default-page-size: 15
        max-page-size: 250
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/house_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  liquibase:
    change-log: "classpath:db/changelog/changelog-root.yml"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method