hibernate:
  connection:
    url: jdbc:postgresql://127.0.0.1:5432/house_db
    username: postgres
    password: postgres
  driver_class: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
